spring:
  datasource:
    url: jdbc:h2:mem:creditdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console.enabled: true

server:
  port: 8084
  servlet:
    context-path: /credit-card-service

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorte: alpha
    operations-sorter: method